language: python
python:
  # We don't actually use the Travis Python, but this keeps it organized.
  - "2.7"
  - "3.5"
  - "3.6"
  - "3.7"
before_install:
  - sudo apt-get update
  # install library dependencies
  - sudo apt-get install libzbar0 make perl
  # Install exiftool
  - wget https://www.sno.phy.queensu.ca/~phil/exiftool/Image-ExifTool-10.98.tar.gz
  - tar -xzf Image-ExifTool-10.98.tar.gz 
  - cd Image-ExifTool-10.98/
  - perl Makefile.PL 
  - make test
  - sudo make install
install:
  # Now install miniconda
  # We do this conditionally because it saves us some downloading if the
  # version is the same.
  - if [[ "$TRAVIS_PYTHON_VERSION" == "2.7" ]]; then
      wget https://repo.continuum.io/miniconda/Miniconda2-latest-Linux-x86_64.sh -O miniconda.sh;
    else
      wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
    fi
  - bash miniconda.sh -b -p $HOME/miniconda
  - source "$HOME/miniconda/etc/profile.d/conda.sh"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  # Useful for debugging any issues with conda
  - conda info -a

  # Finally create conda environment and run tests
  - conda env create -q micasense_conda_env.yml
  - conda activate micasense
  - python setup.py install

script:
  # Your test script goes here
  - pytest